# Generated by Django 5.2.11 on 2026-02-28 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_ticket_encrypted', models.TextField()),
                ('credits_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100)),
                ('is_negative', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('adjudication_date', models.DateTimeField(blank=True, null=True)),
                ('raw_api_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.tender')),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('SIMPLE', 'Análisis Nivel 1 (Ficha)'), ('DEEP', 'Análisis Nivel 2 (Bases)')], max_length=10)),
                ('score', models.IntegerField(default=0)),
                ('result_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='core.tender')),
            ],
        ),
        migrations.CreateModel(
            name='TenderManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ANALYZED', 'Analizada'), ('FAVORITE', 'Favorita'), ('ARCHIVED', 'Archivada')], default='ANALYZED', max_length=20)),
                ('status_bases', models.BooleanField(default=False)),
                ('status_annexes', models.BooleanField(default=False)),
                ('status_sent', models.BooleanField(default=False)),
                ('internal_notes', models.TextField(blank=True)),
                ('outcome', models.CharField(blank=True, choices=[('WON', 'Ganada'), ('LOST', 'Perdida'), ('NOT_PRESENTED', 'No Presentada')], max_length=20, null=True)),
                ('bid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('feedback_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='management', to='core.tender')),
            ],
        ),
    ]
